# Configure Security defaults here
# These defaults are based on the CIS and other frameworks

$defaults=[
  "/etc/default/passwd,MAXWEEKS,=,13",
  "/etc/default/passwd,MINWEEKS,=,1",
  "/etc/default/passwd,WARNWEEKS,=,4",
  "/etc/default/passwd,PASSLENGTH,=,8",
  "/etc/default/passwd,NAMECHECK,=,YES",
  "/etc/default/passwd,HISTORY,=,10",
  "/etc/default/passwd,MINDIFF,=,3",
  "/etc/default/passwd,MINALPHA,=,2",
  "/etc/default/passwd,MINUPPER,=,1",
  "/etc/default/passwd,MINLOWER,=,1",
  "/etc/default/passwd,MINDIGIT,=,1",
  "/etc/default/passwd,MINNONALPHA,=,1",
  "/etc/default/passwd,MAXREPEATS,=,0",
  "/etc/default/passwd,WHITESPACE,=,YES",
  "/etc/default/passwd,DICTIONDBDIR,=,/var/passwd",
  "/etc/default/passwd,DICTIONLIST,=,/usr/share/lib/dict/words",
  "/etc/default/login,UMASK,=,077",
  "/etc/default/login,SYSLOG_FAILED_LOGINS,=,0",
  "/etc/default/login,SYSLOG,=,YES",
  "/etc/default/login,PASSREQ,=,YES",
  "/etc/default/login,SLEEPTIME,=,4",
  "/etc/default/login,RETRIES,=,3",
  "/etc/default/login,DISABLETIME,=,3600",
  "/etc/default/login,CONSOLE,=,/dev/console",
  "/etc/default/sendmail,QUEUEINTERVAL,=,15",
  # Solaris 10 and below
  "/etc/default/inetinit,TCP_STRONG_ISS,=,2",
  # Solaris 9 and below
  "/etc/default/inetd,ENABLE_CONNECTION_LOGGING,=,YES",
  # Solaris 10
  "/etc/default/su,SYSLOG,=,YES",
  "/etc/default/cron,CRONLOG,=,YES",
  "/etc/default/keyserv,ENABLE_NOBODY_KEYS,=,NO",
  "/etc/default/telnetd,BANNER,=,/etc/issue",
  "/etc/default/power,PMCHANGEPERM,=,-",
  "/etc/default/power,CPRCHANGEPERM,=,-",
  "/etc/default/sys-suspend,PERMS,=,-",
  # SSH security settings
  "/etc/ssh/sshd_config,Protocol, ,2",
  "/etc/ssh/sshd_config,X11Forwarding, ,no",
  "/etc/ssh/sshd_config,MaxAuthTries, ,3",
  "/etc/ssh/sshd_config,MaxAuthTriesLog, ,0",
  "/etc/ssh/sshd_config,RhostsAuthentication, ,no",
  "/etc/ssh/sshd_config,IgnoreRhosts, ,yes",
  "/etc/ssh/sshd_config,StrictModes, ,yes",
  "/etc/ssh/sshd_config,AllowTcpForwarding, ,no",
  "/etc/ssh/sshd_config,ServerKeyBits, ,1024",
  "/etc/ssh/sshd_config,GatewayPorts, ,no",
  "/etc/ssh/sshd_config,RhostsRSAAuthentication, ,no",
  "/etc/ssh/sshd_config,PermitRootLogin, ,no",
  "/etc/ssh/sshd_config,PermitEmptyPasswords, ,no",
  "/etc/ssh/sshd_config,PermitUserEnvironment, ,no",
  "/etc/ssh/sshd_config,HostbasedAuthentication, ,no",
  "/etc/ssh/sshd_config,Banner, ,/etc/issue",
  "/etc/ssh/sshd_config,PrintMotd, ,no",
  "/etc/ssh/sshd_config,ClientAliveInterval, ,300",
  "/etc/ssh/sshd_config,ClientAliveCountMax, ,0",
  "/etc/ssh/sshd_config,LogLevel, ,VERBOSE",
  "/etc/ssh/sshd_config,RSAAuthentication, ,no",
  "/etc/ssh/sshd_config,UsePrivilegeSeparation, ,yes",
  "/etc/ssh/sshd_config,LoginGraceTime, ,120",
  "/etc/ssh/sshd_config,ServerKeyBits, ,1024",
  # /etc/system Security settings
  "/etc/system,set nfssrv:nfs_portmon,=,1",
  "/etc/system,set noexec_user_stack_log,=,1",
  "/etc/system,set noexec_user_stack,=,1"
]
